// ~vstManager.addToGroup('Winds', "SWAM Contrabassoon 3 03");
// ~vstManager.addToGroup('Winds', "SWAM Contrabassoon 3 04");
// ~vstManager.addToGroup('Winds', "SWAM Bass Clarinet 3 04");

// // save to group
//         ~vstManager.createGroup('Winds', "SWAM Alto Flute 3 02,SWAM Alto Flute 3 03");

// print a warning that you should not be seeing this message
"WARNING: You should not be seeing this message".postln;
